-- DDL
-- 1. 계열 정보를 저장할 카테고리 테이블 만들기
CREATE TABLE TB_CATEGORY(
    NAME VARCHAR2(10),
    USE_YN CHAR(1) DEFAULT 'Y'
);

-- 2. 과목 구분을 저장할 테이블 만들기
CREATE TABLE TB_CLASS_TYPE(
    NO VARCHAR2(5) PRIMARY KEY,
    NAME VARCHAR2(10)
);

-- 3. TB_CATEGORY 테이블의 NAME 컬럼에 PRIMARY KEY 생성
ALTER TABLE TB_CATEGORY ADD CONSTRAINT PK_TC_NAME PRIMARY KEY(NAME);

-- 4. TB_CLASS_TYPE 테이블의 NAME 컬럼에 NULL 값이 들어가지 않도록 하기
ALTER TABLE TB_CLASS_TYPE MODIFY NAME CONSTRAINT NN_TCT_NAME NOT NULL;

-- 5. 두 테이블에서 컬럼 명이 NO인 것은 기존 타입을 유지하면서 크기를 10으로, 컬럼 명이 NAME인 것은 기존 타입을 유지하면서 20으로 변경
ALTER TABLE TB_CATEGORY
MODIFY NAME VARCHAR2(20);

ALTER TABLE TB_CLASS_TYPE
MODIFY NO VARCHAR2(10)
MODIFY NAME VARCHAR2(20);

-- 6. 두 테이블의 NO 컬럼과 NAME 컬럼의 이름을 각각 TB_를 제외한 테이블 이름이 앞에 붙은 형태로 만들기
ALTER TABLE TB_CATEGORY
RENAME COLUMN NAME TO CATEGORY_NAME;

ALTER TABLE TB_CLASS_TYPE
RENAME COLUMN NAME TO CLASS_TYPE_NAME;
ALTER TABLE TB_CLASS_TYPE
RENAME COLUMN NO TO CLASS_TYPE_NO;

-- 7. TB_CATEGORY, TB_CLASS_TYPE 테이블의 PRIMARY KEY 이름 변경
SELECT * FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'TB_CATEGORY'
      AND CONSTRAINT_TYPE = 'P';

ALTER TABLE TB_CATEGORY
RENAME CONSTRAINT PK_TC_NAME TO PK_CATEGORY_NAME;

SELECT * FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'TB_CLASS_TYPE'
      AND CONSTRAINT_TYPE = 'P';

ALTER TABLE TB_CLASS_TYPE
RENAME CONSTRAINT SYS_C007710 TO PK_CLASS_TYPE_NO;

-- 8. INSERT문 수행
INSERT INTO TB_CATEGORY VALUES('공학', 'Y');
INSERT INTO TB_CATEGORY VALUES('자연과학', 'Y');
INSERT INTO TB_CATEGORY VALUES('의학', 'Y');
INSERT INTO TB_CATEGORY VALUES('예체능', 'Y');
INSERT INTO TB_CATEGORY VALUES('인문사회', 'Y');

COMMIT;

-- 9. TB_DEPARTMENT의 CATEGORY 컬럼이 TB_CATEGORY 테이블의 CATEGORY_NAME 컬럼을 부모 값으로 참조하도록 FOREING KEY 지정
ALTER TABLE TB_DEPARTMENT ADD CONSTRAINT FK_DEPARTMENT_CATEGORY FOREIGN KEY(CATEGORY) REFERENCES TB_CATEGORY(CATEGORY_NAME);









