-- DDL (ALTER, DROP)
-- ALTER : 객체 수정 / DROP : 객체 삭제
-- 컬럼 추가/수정/삭제
SELECT * FROM DEPT_COPY;

-- 컬럼 추가
ALTER TABLE DEPT_COPY 
ADD (CNAME VARCHAR2(20)); -- 값이 NULL로 들어감

ALTER TABLE DEPT_COPY 
ADD (LNAME VARCHAR2(40) DEFAULT '한국'); -- DEFAULT 값 설정 가능

-- 컬럼 수정
/*
DEPT_ID	CHAR(2 BYTE)
DEPT_TITLE	VARCHAR2(35 BYTE)
LOCATION_ID	CHAR(2 BYTE)
CNAME	VARCHAR2(20 BYTE)
LNAME	VARCHAR2(40 BYTE)
*/

ALTER TABLE DEPT_COPY
MODIFY DEPT_ID CHAR(3);

ALTER TABLE DEPT_COPY
MODIFY DEPT_TITLE VARCHAR2(30)
MODIFY LOCATION_ID VARCHAR2(2)
MODIFY CNAME CHAR(20)
MODIFY LNAME DEFAULT '미국';
-- 크기, 자료형, DEFAULT 값 모두 변경 가능

INSERT INTO DEPT_COPY
VALUES('D10', '총괄부', 'L1', NULL, DEFAULT);

ALTER TABLE DEPT_COPY
MODIFY DEPT_TITLE VARCHAR2(10); -- ORA-01441: 일부 값이 너무 커서 열 길이를 줄일 수 없음
-- 컬럼의 크기를 줄일 때 그 안에 있는 데이터 중 단 하나라도 크기를 넘는 경우 줄어들지 않음

-- 컬럼 삭제
-- 데이터가 컬럼 안에 존재해도 삭제 가능
CREATE TABLE DEPT_COPY2
AS SELECT * FROM DEPT_COPY;

SELECT * FROM DEPT_COPY2;

ALTER TABLE DEPT_COPY2
DROP COLUMN CNAME;

ALTER TABLE DEPT_COPY2
DROP COLUMN LOCATION_ID;

ALTER TABLE DEPT_COPY2
DROP COLUMN LNAME;

ALTER TABLE DEPT_COPY2
DROP COLUMN DEPT_ID;

ALTER TABLE DEPT_COPY2
DROP COLUMN DEPT_TITLE; -- ORA-12983: 테이블에 모든 열들을 삭제할 수 없습니다
-- 테이블은 최소 한 개 이상의 컬럼을 갖고 있어야 해서 더이상 삭제 블가능

ROLLBACK; -- 복구가 안 됨
-- COMMIT, ROLLBACK은 DML에 관련된 애들만 가능

CREATE TABLE TB1(
    PK1 NUMBER PRIMARY KEY,
    COL1 NUMBER,
    CHECK(PK1 > 0 AND COL1 > 0)
);

CREATE TABLE TB2(
    PK2 NUMBER PRIMARY KEY,
    COL2 NUMBER,
    FK2 NUMBER REFERENCES TB1,
    CHECK(PK2 > 0 AND COL2 > 0)
);

ALTER TABLE TB1 DROP COLUMN PK1; -- ORA-12992: 부모 키 열을 삭제할 수 없습니다
-- 제약 조건이 걸려 있음
ALTER TABLE TB2 DROP COLUMN PK2; -- ORA-12991: 열이 다중-열 제약 조겅에 참조되었습니다

-- 제약 조건까지 같이 삭제
ALTER TABLE TB1
DROP COLUMN PK1 CASCADE CONSTRAINTS; -- 삭제 가능

SELECT * FROM TB1; 

-- 제약조건 추가
-- DEPT_COPY 테이블에 제약조건 추가
-- PRIMARY KEY를 DEPT_ID에 추가 (PK_DCOPY_DID)
-- UNIQUE를 DEPT_TITLE에 추가 (UQ_DCOPY_DTITLE)
-- NOT NULL을 LNAME에 추가 (NN_DCOPY_LNAME)
ALTER TABLE DEPT_COPY ADD CONSTRAINT PK_DCOPY_DID PRIMARY KEY(DEPT_ID);
ALTER TABLE DEPT_COPY ADD CONSTRAINT UQ_DCOPY_DTITLE UNIQUE(DEPT_TITLE);
ALTER TABLE DEPT_COPY MODIFY LNAME CONSTRAINT NN_DCOPY_LNAME NOT NULL;

-- 한 번에 쓸 수 있음
ALTER TABLE DEPT_COPY 
ADD CONSTRAINT PK_DCOPY_DID PRIMARY KEY(DEPT_ID)
ADD CONSTRAINT UQ_DCOPY_DTITLE UNIQUE(DEPT_TITLE) -- 빨간 줄 편집기 오류
MODIFY LNAME CONSTRAINT NN_DCOPY_LNAME NOT NULL;

-- 제약 조건 삭제
ALTER TABLE DEPT_COPY
DROP CONSTRAINT PK_DCOPY_DID;

-- 한 번에 삭제
ALTER TABLE DEPT_COPY
DROP CONSTRAINT UQ_DCOPY_DTITLE
DROP CONSTRAINT SYS_C007695
MODIFY LNAME NULL;
-- DROP를 MODIFY 아래에 쓰면 오류 발생
-- ORA-00933: SQL 명령어가 올바르게 종료되지 않았습니다

-- 이름 변경
SELECT * FROM DEPT_COPY;

ALTER TABLE DEPT_COPY
RENAME COLUMN DEPT_TITLE TO DEPT_NAME;

COMMIT;
-- 제약조건 이름 변경
ALTER TABLE DEPT_COPY
RENAME CONSTRAINT SYS_C007696 TO NN_DCOPY_LID;
--             뭐에 대해 RENAME 할지

ALTER TABLE DEPT_COPY
RENAME TABLE DEPT_COPY TO DEPT_TEST; -- 오류

ALTER TABLE DEPT_COPY
RENAME TO DEPT_TEST; -- 이미 위에 TABLE DEPT_COPY를 적어 줬기 때문에 또 명시 안 해도 됨
-- 테이블 이름 변경 가능

-- 테이블 삭제
DROP TABLE DEPT_TEST;

-- 제약 조건 삭제
DROP TABLE DEPT_TEST 
CASCADE CONSTRAINTS;
