-- DML
-- 1. 과목 유형 테이블에 데이터 입력
--INSERT INTO TB_CLASS_TYPE (CLASS_TYPE_NO, CLASS_TYPE_NAME) VALUES (01, '전공필수');
--INSERT INTO TB_CLASS_TYPE (CLASS_TYPE_NO, CLASS_TYPE_NAME) VALUES (02, '전공선택');
--INSERT INTO TB_CLASS_TYPE (CLASS_TYPE_NO, CLASS_TYPE_NAME) VALUES (03, '교양필수');
--INSERT INTO TB_CLASS_TYPE (CLASS_TYPE_NO, CLASS_TYPE_NAME) VALUES (04, '교양선택');
--INSERT INTO TB_CLASS_TYPE (CLASS_TYPE_NO, CLASS_TYPE_NAME) VALUES (05, '논문지도');

INSERT INTO TB_CLASS_TYPE (CLASS_TYPE_NO, CLASS_TYPE_NAME)
SELECT 01, '전공필수' FROM DUAL UNION ALL 
SELECT 02, '전공선택' FROM DUAL UNION ALL 
SELECT 03, '교양필수' FROM DUAL UNION ALL 
SELECT 04, '교양선택' FROM DUAL UNION ALL 
SELECT 05, '논문지도' FROM DUAL;

-- 2. 학생 일반정보 테이블 생성
CREATE TABLE TB_학생일반정보 
AS SELECT STUDENT_NO, STUDENT_NAME, STUDENT_ADDRESS
   FROM TB_STUDENT;

-- 3. 국어국문학과 학생들의 정보만이 포함되어 있는 학과 정보 테이블 생성
CREATE TABLE TB_국어국문학과
AS SELECT STUDENT_NO, STUDENT_NAME, 19 || SUBSTR(STUDENT_SSN, 1, 2) 출생년도, PROFESSOR_NAME
   FROM TB_STUDENT
        JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
        LEFT JOIN TB_PROFESSOR ON (COACH_PROFESSOR_NO = PROFESSOR_NO)
   WHERE DEPARTMENT_NAME = '국어국문학과';

CREATE TABLE TB_국어국문학과
AS SELECT STUDENT_NO, STUDENT_NAME, 19 || SUBSTR(STUDENT_SSN, 1, 2) 출생년도, PROFESSOR_NAME
   FROM TB_STUDENT S, TB_DEPARTMENT D, TB_PROFESSOR
   WHERE COACH_PROFESSOR_NO = PROFESSOR_NO(+)
         AND S.DEPARTMENT_NO = D.DEPARTMENT_NO
         AND DEPARTMENT_NAME = '국어국문학과';
         
/* 그룹 합수를 사용하지 않았는데 별칭을 지정해 주어야 하는 이유가 무엇인지 

CREATE TABLE TB_국어국문학과2
AS SELECT STUDENT_NO, STUDENT_NAME, TO_CHAR(TO_DATE(SUBSTR(STUDENT_SSN, 1, 6)), 'YYYY'), NVL(PROFESSOR_NAME, '지도교수 없음')
   FROM TB_STUDENT TS
        LEFT JOIN TB_PROFESSOR TP ON(COACH_PROFESSOR_NO = PROFESSOR_NO)
        LEFT JOIN TB_DEPARTMENT TD ON(TS.DEPARTMENT_NO = TD.DEPARTMENT_NO)
   WHERE TD.DEPARTMENT_NAME = '국어국문학과';
*/
         
-- 4. 현 학과들의 정원 10% 증가
UPDATE TB_DEPARTMENT 
SET CAPACITY = ROUND(CAPACITY * 1.1);

-- 5. 학번이 A413042인 학생의 주소지 변경
UPDATE TB_STUDENT
SET STUDENT_ADDRESS = '서울시 종로구 숭인동 181-21'
WHERE STUDENT_NO = 'A413042';

-- 6. 학생 정보 테이블에서 주민번호 뒷자리 삭제
UPDATE TB_STUDENT
SET STUDENT_SSN = SUBSTR(STUDENT_SSN, 1, INSTR(STUDENT_SSN, '-')-1);

-- 7. 의학과 김명훈 학생의 피부생리학 점수 수정
UPDATE TB_GRADE
SET POINT = 3.5
WHERE STUDENT_NO = (SELECT STUDENT_NO
                    FROM TB_STUDENT
                         JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
                    WHERE STUDENT_NAME = '김명훈'
                          AND DEPARTMENT_NAME = '의학과')
      AND CLASS_NO = (SELECT CLASS_NO
                      FROM TB_CLASS
                      WHERE CLASS_NAME = '피부생리학')
      AND TERM_NO = '200501';

/*
SELECT STUDENT_NAME, CLASS_NAME, DEPARTMENT_NAME, POINT, TERM_NO
FROM TB_STUDENT
     JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
     JOIN TB_GRADE USING(STUDENT_NO)
     JOIN TB_CLASS USING(CLASS_NO)
WHERE STUDENT_NAME = '김명훈'
      AND DEPARTMENT_NAME = '의학과';
*/

-- 8. 휴학생들의 성적 항목 제거
UPDATE TB_GRADE 
SET POINT = NULL
WHERE STUDENT_NO IN(SELECT STUDENT_NO
                    FROM TB_STUDENT
                    WHERE ABSENCE_YN = 'Y');
/*
SELECT STUDENT_NAME, POINT, ABSENCE_YN
FROM TB_GRADE
     JOIN TB_STUDENT USING(STUDENT_NO)
WHERE ABSENCE_YN = 'Y';
*/




